### ISSUE TITLE
Design Docs Review - Sample State

### ISSUE THREAD

**Issue by jliversi** [hquddus93/Trailmix#2]
Great work on your sample state! Just a few notes:
- [x] Change all snake_case to camelCase (this will all be on your frontend and we should be using camelCase in js).
- [x] Include myList details in sample state (probably in the form of myListIds under each user).
- [x] Include genreIds under videos
- [ ] If you'll have shows, you'll also need a table for seasons (this is a note for schema), and once that's added, you should also have this information included in your frontend state.

**Comment by hquddus93** [comment]
ok I changed the schema so that on my videos table instead of show_id there is an optional season_id and then on the seasons table there is a show_id. so a video will belong to a season, a season will belong to a show, and a show will have many seasons and many videos through seasons. I updated the sample states to reflect this change as well.
